# Generated by Django 3.1.5 on 2022-03-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_auto_20220326_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description_text',
            field=models.CharField(default='Description', max_length=200),
        ),
    ]
