# Generated by Django 3.1.5 on 2022-04-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_auto_20220326_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Lesson',
            field=models.TextField(default='Enter a Text', max_length=1000),
        ),
    ]
